### ISSUE TITLE
How to compile production?

### ISSUE THREAD

**Issue by omqmo** [nxarch/nest-nguniversal#26]
I can't understand, does this module allow compiling for production? Or is it just for development?

**Comment by denny99** [comment]
Did you find a solution?

I have major issues with this.

My commands are:

nx build frontend
nx ssr frontend
nx build backend

To run the final container i just use node dist/apps/backend/main

This works. Nearly. 
My Mongoose Annotations are totally broken. Everything else is fine.
This issue does not happen when using serve-ssr, it just happens with the regular build process.
